file_url.settings:
  type: config_object
  label: 'File URL settings'
  mapping:
    dereference_host:
      type: string
      label: 'Dereference host'

field.storage_settings.file_url:
  type: field.storage_settings.file
  label: 'File URL settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

field.field_settings.file_url:
  type: field.field_settings.file
  label: 'File URL settings'

field.widget.settings.file_url_generic:
  type: field.widget.settings.file_generic
  label: 'File URL generic widget'
  mapping:
    add_new_label:
      type: label
      label: 'New item form label'

field.formatter.settings.file_url_default:
  type: field.formatter.settings.file_default
  label: 'File URL generic formatter'
  mapping:
    mode:
      type: string
      labe: 'File display mode'
